### ISSUE TITLE
Cython compile error during setup

### ISSUE THREAD

**Issue by leloup314** [SiLab-Bonn/testbeam_analysis#107]
After I did a fresh clone of `testbeam_analysis` and `conda update conda && conda update --all` I get the following error when doing `python setup.py develop` in the `testbeam_anaylsis` folder:

testbeam_analysis/cpp/analysis_functions.pyx:59:92: Invalid type.
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    Extension('testbeam_analysis.analysis_functions', ['testbeam_analysis/cpp/analysis_functions.pyx'])
  File "/home/leloup/miniconda2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
    cythonize_one(*args)
  File "/home/leloup/miniconda2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: testbeam_analysis/cpp/analysis_functions.pyx

**Comment by laborleben** [comment]
Use 
```from testbeam_analysis.cpp.data_struct cimport numpy_hit_info, numpy_cluster_info```
instead of
```from data_struct cimport numpy_hit_info, numpy_cluster_info```
in https://github.com/SiLab-Bonn/testbeam_analysis/blob/development/testbeam_analysis/cpp/analysis_functions.pyx.

Does it solve your issue?

**Comment by leloup314** [comment]
Yes, this solves the issue!

**Comment by laborleben** [comment]
OK, I'll prepare a PR.
