### ISSUE TITLE
Track Quality not set properly 

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/testbeam_analysis#11]
event 2845 has wrong quality and track is built wrong.
see attachments 
[tracks_with_alignment.zip](https://github.com/SiLab-Bonn/testbeam_analysis/files/144527/tracks_with_alignment.zip)

**Comment by DavidLP** [comment]
This might be also related to https://github.com/SiLab-Bonn/testbeam_analysis/issues/7

**Comment by laborleben** [comment]
still broken
[broken_event.zip](https://github.com/SiLab-Bonn/testbeam_analysis/files/144820/broken_event.zip)

**Comment by laborleben** [comment]
This is also related to weird residuals where residuals show hits in great distances.

**Comment by laborleben** [comment]
ok seems to work fine now.
