### ISSUE TITLE
Exclude DUT hit should be true as std. setting

### ISSUE THREAD

**Issue by coquelin77** [SiLab-Bonn/testbeam_analysis#112]
Should be better std. settting

**Comment by DavidLP** [comment]
Maybe.

**Comment by leloup314** [comment]
Is this not the case for you? At least [here](https://github.com/SiLab-Bonn/testbeam_analysis/blob/development/testbeam_analysis/track_analysis.py#L138) it is already set to `True` as default.

**Comment by leloup314** [comment]
Apparently I set this to `False` manually in [here](https://github.com/SiLab-Bonn/testbeam_analysis/blob/development/testbeam_analysis/gui/tab_widgets/analysis_tabs.py#L583). Should this also not be fixed?
