### ISSUE TITLE
GUI col and row ranges in the efficiency tab

### ISSUE THREAD

**Issue by coquelin77** [SiLab-Bonn/testbeam_analysis#118]
ranges are only one way sliders, these cannot be used to set a range

**Comment by leloup314** [comment]
The docstring of `col_range` and  `row_range` says `iterable` so only one pair of integers for all DUTs? E.g. `col_range=(10, 70)` or can this also be an `iterable of iterables` DUT-wise like `col_range=[(10, 70), (10, 55), (10, 80), (20, 70)]` where the index indicates the DUT index?

**Comment by DavidLP** [comment]
Yes!

**Comment by leloup314** [comment]
@DavidLP I'm reopening since I have a question regarding the range: Are we going from 0 to N-1 or 1 to N? Let's say for FE-I4 column range from 0 to 79 or 1 to 80? I just realised I made the minimum and maximum of the ranges from 0 to N which doesn't make sense I guess.

**Comment by DavidLP** [comment]
Not sure, depends on if we want to have inclusive or exclusive limits on max value. Usually python, numpy and matplotlib have (min, max+1) everywhere, I think. So I would  go with this convention. Should be mentioned in help Text of function.

**Comment by leloup314** [comment]
I guess then it's fine like it is now.
