### ISSUE TITLE
Interference with pyBAR clusterizer

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/testbeam_analysis#12]
I had an old version of pyBAR installed that is still containing the pixel clusterizer.
In parallel, I had the pixel_clusterizer version 2.3.0 installed. Both added to the python path.

Under this circumstances, the pixel clusterizer from pyBAR was preferred. Unfortunately the pyBAR clusterizer has a bug which gives an offset to the column and row cluster mean.

I leave this message here as a warning. Possible bug fix wanted.

Side note: Christian was experiencing this bug for a while and could not explain the offset in the Tracklets file.

**Comment by DavidLP** [comment]
Where is a bug fix wanted? If you have the newest versions there is no bug?
