### ISSUE TITLE
PyQt5 - missing requirement

### ISSUE THREAD

**Issue by owtscharenko** [SiLab-Bonn/testbeam_analysis#121]
PyQt5 is needed for gui, but  not installed upon installation of testbeam_analysis. It is also not part of the requirements.txt

**Comment by leloup314** [comment]
I always assumed this was one of `matplotlibs` dependencies but I just figured its not. So we should add `pyqt` to the `requirements.txt` This should install PyQt version 5

**Comment by laborleben** [comment]
I want to make you aware that the issue with PyQt package is more complicated. The name `pyqt` is just package name for PyQt Version 5 in the Anaconda/Miniconda universe, whereas in the pip universe the name is `PyQt5`. Choosing one universe will break the installation requirements for the other. There is no satisfying solution available. Check out this link: https://github.com/uvemas/ViTables/issues/79

**Comment by DavidLP** [comment]
Because of what Jens said we cannot require pyqt5. The anaconda maintainers fail to see the issue and we have to live with it: https://github.com/ContinuumIO/anaconda-issues/issues/1554

**Comment by laborleben** [comment]
@DavidLP Thanks for the second link. Edit: Just saw, it was already posted in the ViTables thread.
