### ISSUE TITLE
GUI: not all DUT tabs visible

### ISSUE THREAD

**Issue by owtscharenko** [SiLab-Bonn/testbeam_analysis#122]
On my 13'' display a maximum 5 of DUT tabs are displayed in the right half of the GUI window. For more planes it is a hassle to get to the correct tab.

**Comment by leloup314** [comment]
Well, there is only limited space for tabs on a tab bar, at some point they are hidden and can only be reached by some left/right button. But I agree that the current solution is not optimal since the buttons are tiny and not well placed. This is referring to the setup tab, right?

**Comment by leloup314** [comment]
This has been moved to #63. Closing.
