### ISSUE TITLE
Fix virtual hits

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/testbeam_analysis#13]
Virtual hits are set by putting column = row = charge = 0. This combination can (although unlikely) happen after alignment. I would propose to signal virtual hits with column = row = 0. and charge = -1.

**Comment by laborleben** [comment]
why not np.nan? they are floats, right?

**Comment by DavidLP** [comment]
Jeh, true. Good idea. The colum/rows are floats.

**Comment by DavidLP** [comment]
Since this is a very rare bug not really changing the result but needs a lot of code changes, this will not be done in any time soon. Low prioriy!

**Comment by DavidLP** [comment]
Fixed.
