### ISSUE TITLE
Track DUT intersections should take rotations into account

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/testbeam_analysis#19]
So far the track extrapolation does not consider any DUT rotation. That is wrong.

**Comment by lvigani** [comment]
Do you mean rotations from the coarse alignment?

**Comment by DavidLP** [comment]
Hi Luigi ;-) Yes. But it will be solved in the comit in a few minutes.

**Comment by lvigani** [comment]
Cool!

**Comment by DavidLP** [comment]
I changed now the track definition (also in view of the future Kalman filter) to have the offset at the DUT intersection. This has the advantage that one does not have to do the track interpolation for each result_analysis function.

**Comment by DavidLP** [comment]
Fixed
