### ISSUE TITLE
Residual fit plot

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/testbeam_analysis#28]
This plot clearly shows a median RMS that is wrong when overlayed to the 2D histogram. Most likely the plotting is wrong.
![capture](https://cloud.githubusercontent.com/assets/6951141/16814184/f7a77a12-4934-11e6-98ff-728038fba88c.JPG)

**Comment by laborleben** [comment]
was fixed by commit https://github.com/SiLab-Bonn/testbeam_analysis/commit/2b89bc759c20ccc56424603d48d92ce81182219d
