### ISSUE TITLE
Binning of histograms under windows

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/testbeam_analysis#31]
With the Anaconda Python 2.7 release under Windows the  following does not work

```
np.histogram(difference[:, 0], bins="auto")
```

**Comment by laborleben** [comment]
tested on another Windows PC and bins="auto" is supported and works.

**Comment by DavidLP** [comment]
Supported or working? It is also supported on my PC but not working

**Comment by DavidLP** [comment]
I think this is somewhat fixed, no?

**Comment by laborleben** [comment]
numpy >=1.11.
