### ISSUE TITLE
Gamma correction with wrong sign when one axis is inverted

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/testbeam_analysis#33]

**Comment by laborleben** [comment]
a possible workaround is:
gamma /= np.sign(m_xx) * np.sign(m_yy) * np.sign(m_xy) * np.sign(m_yx) * (factor_xy + factor_yx)

**Comment by DavidLP** [comment]
That is what I expected. One cannot just invert one axis, because it changes the handedness.

**Comment by DavidLP** [comment]
It does not make sense to invert one axis in the data, since this is unphysical. This does not have to work.
