### ISSUE TITLE
Calculation of slope

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/testbeam_analysis#34]
1. should the slope vector be a normalized vector? See https://github.com/SiLab-Bonn/testbeam_analysis/blob/44eacadb6e7743b28b889258fa88d18934e9194d/testbeam_analysis/track_analysis.py#L657

2. What about https://github.com/SiLab-Bonn/testbeam_analysis/blob/44eacadb6e7743b28b889258fa88d18934e9194d/testbeam_analysis/track_analysis.py#L655, where the slope vector is divided by its third component?

**Comment by laborleben** [comment]
2. Ok, this is clear to me when you assume that the plane is parallel to x-y-plane.

**Comment by DavidLP** [comment]
Well spotted, I opened a bug report #34

**Comment by DavidLP** [comment]
1. We can normalize the direction vector of the track (slope), but we do not have to.

**Comment by laborleben** [comment]
OK, I see, I'll if the normalization has some influence on further data processing.

**Comment by DavidLP** [comment]
Questions answered.
