### ISSUE TITLE
Regressions in development branch

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/testbeam_analysis#39]
The development branch suffered a lot of regressions ~~and cannot be used productively right now~~. There is an experimental branch, but the functions there are work in progress, have a lot of debug prints, and are not tested.

The following points have to be fixed:

- [x] Examples have to work again
- [x] Results have to be cross checked with later analysis
- [ ] Merging of cleaned up experimental into development has to be done. ~~Right now development is a messy, not working mixture of both (e.g. efficiency calculation does not work)~~

**Comment by DavidLP** [comment]
Cross check with old data (FE-I4 telescope + LFoundry sensor) and simulation show the same efficiency and similar # tracks etc. Thus results can be trusted again.

**Comment by DavidLP** [comment]
Simulation example and FE-I4 telescope example do work again with good results.

**Comment by DavidLP** [comment]
EUtelelecope data example works with good results. For reference:
- Residuals after prealignment:
``` 
column = [21.5 ; 7.9; 17.2; 17.8; 17.7; 36.0] um
row = [19.8; 6.9; 21.9; 21.7; 22.9; 50.9] um
```
- Residuals after alignment with all DUTs in fit and Chi2 track cut: 
``` 
column = [17.1; 6.3; 8.2; 8.0; 6.4; 17.3] um
row = [17.1;  6.3; 8.2; 8.1; 6.3; 17.2] um
``` 
- Residuals after alignment with neighbouring DUTs in fit: 
``` 
column = [12.9; 6.5; 6.5; 6.4; 6.6; 13.1] um
row = [12.8; 6.5; 6.6; 6.4; 6.5; 13.0] um
```

**Comment by DavidLP** [comment]
All Examples with shipped data have unit tests now.

**Comment by DavidLP** [comment]
@laborleben Code is in good health now and was released. Feel free to merge your experimental branch now.

**Comment by DavidLP** [comment]
@laborleben : I compared `development` to `experimental`. I do not see that much of a difference in features:

1. Some fitting limits in `prealignment` that are used in `calculate_residuals`
2. Unifinished refactoring of `calculate_efficiency`. What does it do?

Mayor differences:
- `track_quality` definition is different
- `dut_alignment.alignment` refactoring or are also features added?

I would just cherry pick some lines of code of `experimental` for `development` and then abandon `experimental`. Ok?

**Comment by laborleben** [comment]
The branch needs a rebase, because you did some changes that produces conflicts. I will clean up the experimental branch and check for errors again.

**Comment by laborleben** [comment]
Most of the smaller things were merge into the development branch. I will create another feature branch with the important changes from the experimental branch.

**Comment by DavidLP** [comment]
I can plot charge maps now?

**Comment by DavidLP** [comment]
The status of the development branch is OK right now. Thus I close.
