### ISSUE TITLE
Make the analysis work nicer with different devices

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/testbeam_analysis#4]
To support devices with different pixel geometries more easily the analysis will be changed to um instead of pixel indices. The pixel geometry definition is then not needed for every function using clustered hits, thus making the data more readable.

**Comment by laborleben** [comment]
nicer outputs for correlation plots, setting aspect ratio possible

**Comment by DavidLP** [comment]
The points of this enhancement are implemented in the actual development.
