### ISSUE TITLE
Result analysis: Track angle

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/testbeam_analysis#46]
To check the overall alignment a beam angle theta histogram would be useful.

**Comment by YannickDieter** [comment]
Okay. To add this function I will create a new branch 'new_features' okay? Should I create one histogram for all DUTs or better separated histograms for the different DUTs? Also a RMS and MEAN calculation would be useful?

**Comment by DavidLP** [comment]
Tracks are build for a certain device (with different cuts) from the tracks tables. So it makes sense to calculate the track angles for each device, similar how it is done right now for the other [result analysis](https://github.com/SiLab-Bonn/testbeam_analysis/blob/development/testbeam_analysis/result_analysis.py#L20) (parameter `use_duts`). I would call the new branch `track_angle`, or are you planning to add other features?

**Comment by YannickDieter** [comment]
Okay this makes sense. No, but maybe we add more features later.

**Comment by DavidLP** [comment]
> No, but maybe we add more features later.

Then we create a new branch ;-)

**Comment by YannickDieter** [comment]
I pushed the track angle histogram. Is it better to separate calculation and plotting even for this 'small' function? I also created a .h5 file with the fitted means and sigmas from the track angle histogram.

**Comment by DavidLP** [comment]
> I also created a .h5 file with the fitted means and sigmas from the track angle histogram.

Good.

We should always seperate calculations from plotting. This makes a seperation between plotting library / backend etc. from calculations possible.

**Comment by laborleben** [comment]
Separating plotting from the other is probably better. Keep in mind that you need to do all the additional imports otherwise.

**Comment by DavidLP** [comment]
Created a [PR](https://github.com/SiLab-Bonn/testbeam_analysis/pull/47)

**Comment by YannickDieter** [comment]
> We should always seperate calculations from plotting. This makes a seperation between plotting library / backend etc. from calculations possible.

Okay then I will split plotting and calculation.

**Comment by DavidLP** [comment]
Also you could merge the changes from development frequently, since Jens is changing it right now.

**Comment by DavidLP** [comment]
This feature is in development now.
