### ISSUE TITLE
[dut_alignment] Cannot change error / offset cut in interactive pre-alignment

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/testbeam_analysis#58]
When I click on the sliders nothing happens.

**Comment by laborleben** [comment]
This is working on my machine. Can you give a more detailed bug report?
The click may have a short delay because it triggers a refit. Probably you are running heavy jobs in the background and the delay becomes noticeable.

**Comment by laborleben** [comment]
I notice a delay when I run heavy job, but this is in the order of 1s. The usual delay is much shorter.

**Comment by DavidLP** [comment]
> This is working on my machine. Can you give a more detailed bug report?

Take the Mimosa telescope example, change to interactive prealignment, click more than once on error/offset limit slider:

![grafik](https://cloud.githubusercontent.com/assets/6951141/22929865/10813270-f2be-11e6-9f1a-186321e05d2e.png)

It stops responding,

> I notice a delay when I run heavy job, but this is in the order of 1s. The usual delay is much shorter.

Nothing was running besides this. First change was done after ~3s. Then no changes anymore. CPU is idle. So load is not a reason.
