### ISSUE TITLE
What does the new column for track candidates n_hits do?

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/testbeam_analysis#6]

**Comment by ChristianBesp** [comment]
It was planned to do a different kind of track finding where the number of DUT hits was needed (something similar to track_quality)

**Comment by DavidLP** [comment]
Ok. What kind of track finding and what does n_hits correspond to? The number of hits per event in all DUTs?

**Comment by ChristianBesp** [comment]
The idea was to do a cluster-like track finding which under further investigation seemed to be similar to the one we're doing already. It should store the total number of hits in all DUTs for every row (something like `bin(track_quality).count("1")`).

**Comment by ChristianBesp** [comment]
Deleted in commit a56910d9ac99dbc82380c1bfe95788b01348e100
