### ISSUE TITLE
[result_analysis] Mean efficiency calculation

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/testbeam_analysis#61]
The mean efficiency calculation should weight the mean result by the statistics per bin. Otherwise low statistic bins can change the mean efficiency a lot (e.g. imagine only one track in a bin creates either 100% or 0% efficiency). Right now this can be mitigated by requiering a minimum amount of tracks per bin and this number should be set always.

**Comment by laborleben** [comment]
https://de.wikipedia.org/wiki/Will-Rogers-Phänomen 👍

**Comment by DavidLP** [comment]
If you do not give a number on the error of the mean this can happen.

**Comment by owtscharenko** [comment]
would this be solved by weighting single bins with the sum of total tracks and use of a weighted average?

**Comment by laborleben** [comment]
When you mean wighted by the total tracks of each individual bin, then yes, but it is not yet done.

**Comment by DavidLP** [comment]
It is less lines of code to implement this than we wrote here :-D. So far we calculate the mean effiencies of the pixels not of the sensor (yes that is something different). If we want to have the overall efficiency, one can just do:

```python
track_density_with_DUT_hit.sum() / track_density.sum()
```

Right now we do:

```python
(track_density_with_DUT_hit / track_density).mean()
```

**Comment by DavidLP** [comment]
@owtscharenko Did you add any calculation in your code that is worth uploading?

**Comment by DavidLP** [comment]
So found a proper solution that does not require ROOT.

**Comment by DavidLP** [comment]
Implemented
