### ISSUE TITLE
[result_analysis] max_chi2 in calculate_efficiency()

### ISSUE THREAD

**Issue by thirono** [SiLab-Bonn/testbeam_analysis#62]
An error occurs when max_chi2 is used, 
https://github.com/SiLab-Bonn/testbeam_analysis/blob/improvements/testbeam_analysis/result_analysis.py#L780
ValueError: operands could not be broadcast together with shapes (515958,) (8,)

Maybe max_chi2 --> actual_max_ch2 ?

**Comment by DavidLP** [comment]
Yes, that is a bug and the solution

**Comment by DavidLP** [comment]
Actually I do not see a bug. Is it possible that you use a alignment file with a different amount of DUTs? What is the traceback?

**Comment by DavidLP** [comment]
Closed due to inactivity. Feel free to reopen if this is wrong.
