### ISSUE TITLE
Kalman filter prediction does not support tilted planes

### ISSUE THREAD

**Issue by YannickDieter** [SiLab-Bonn/testbeam_analysis#67]
The Kalman filter does not support tilted planes in the prediction step. For the z-position of the planes it is always taken the z-positions from the alignment. For tilted planes this is not true, since there is a dependency of z on the x-y hit position.

**Comment by DavidLP** [comment]
Since we do not have heavily tilted planes in alpha / beta + reference planes close by this simplification should not make results worse. Thus I label this enhancement and not bug.

**Comment by YannickDieter** [comment]
I think we can close this issue, right?

**Comment by DavidLP** [comment]
Sure.
