### ISSUE TITLE
Pre-alignment crashes for different DUT types when fitting

### ISSUE THREAD

**Issue by leloup314** [SiLab-Bonn/testbeam_analysis#70]
![selection_0040](https://cloud.githubusercontent.com/assets/18701435/26377827/3ebb70f0-4012-11e7-83f7-41524ddea180.png)
The pre-alignment crashes whenever there are different DUTs, e.g. 1 FE-I4 and the rest M26 etc.
It does work for FE-I4 only and respectively M26 only. All analysis function before (like in `eutelescope` example) run.

**Comment by DavidLP** [comment]
Do you have data with FE-I4 and Eutel? This is not shipped with TBA.

**Comment by DavidLP** [comment]
This is not a bug, since your try correlating uncorrelated data. But I think that the error message should be more clear. Something like: 'WARNING: No correlation found, cannot fit' and then continue with the other devices. This makes it a possible enhancement.

**Comment by leloup314** [comment]
@laborleben Has this been adressed in the `improvements` branch?

**Comment by DavidLP** [comment]
Done
