### ISSUE TITLE
[GUI] Bugs

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/testbeam_analysis#72]
This issue summarizes all parts that do not work as intended in the GUI. Checked bugs are fixed.

- [x] Crash of the `python.exe` under Windows when doing Noisy Pixel and Clustering analysis with FE-I4 data. Multi-threading related issue in ParallelAnalysisWidget, fixed in a316d82f728183043958099de2f9f71a6223ac56
- [x] Unit tests fail, fixed in 9874ce16ae61761268cb7081b6aaf78b4a251105
- [x] Some tabs are still initialized with incorrect options / incorrect default values
- [x] Traceback and some error outputs are not put into the GUI logger. Likely a handler for the logging module has to be defined?
- [x] Example plot for tracks looks weird
- [x] ImportError when ViTables not installed is not catched:
      ` Traceback (most recent call last):
  File "/usr/bin/vitables", line 37, in <module>
    from PyQt4 import QtGui
ImportError: No module named PyQt4`
- [x] Individual noisy pixel removal will crash if all DUTs are checked to skip.
- [x] Not all exceptions are catched
- [x] Consecutive analysis:
    - [x] Fixed under Linux in 69e54c8e9cc5df35fc1f7a8d6eb04602a09cd195
    - [x] Fixed under Windows in 50e696f77fc6f27b6010d66c8a223ea7c7337774
- [x] Analysis crashes under Windows randomly when plotting (due to threaded plotting), fixed in 50e696f77fc6f27b6010d66c8a223ea7c7337774
- [x] Pressing `CRTL+R` while analysing leads to a freeze (windows, multi process analysis), fixed in 67e34132d6f67f6b4e577c38605f6326fd2aa2da
- [x] Interactive pre-alignment throws exeption, fixed in 91d0e8a529d8c2db0e07786dcebe05d2be4b52c2:
``` python
**Traceback (most recent call last):
  File "/home/davidlp/git/testbeam_analysis/testbeam_analysis/gui/analysis_worker.py", line 63, in work
    pool.apply_async(self.main_func(func, kwargs))
  File "/home/davidlp/git/testbeam_analysis/testbeam_analysis/gui/analysis_widgets.py", line 396, in _call_func
    func(**kwargs)
  File "/home/davidlp/git/testbeam_analysis/testbeam_analysis/dut_alignment.py", line 421, in prealignment
    non_interactive=non_interactive)
  File "/home/davidlp/git/testbeam_analysis/testbeam_analysis/tools/plot_utils.py", line 674, in plot_prealignments
    plt.show()
  File "/home/davidlp/miniconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 253, in show
    return _show(*args, **kw)
  File "/home/davidlp/miniconda2/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 193, in __call__
    self.mainloop()
  File "/home/davidlp/miniconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 162, in mainloop
    signal.signal(signal.SIGINT, signal.SIG_DFL)
ValueError: signal only works in main thread
```
- [x] Option(Multi)SliderWidget needs to be checked regarding double/int validators. Some options (like `max_iterations` in `alignment` NEED int, crashes if slider is changed by accident which results in the options value being float), fixed in 75ad91b4b8834fd04241afbc65e5246308042113
- [x] Noisy pixel mask file is set although noisy mask creation is skipped, fixed in a46e744232904e06a705dd02cf4abc7f7486a4da
- [x] Widget does not abort when exception is thrown, fixed in 69e54c8e9cc5df35fc1f7a8d6eb04602a09cd195
- [x] `CRTL-R` under Linux raises RuntimeError, fixed in d14320cef20eac47f88a0dc6194ea41f42366a6f:
```bash
Traceback (most recent call last):
  File "main.py", line 649, in run_consecutive_analysis
    if self.tw[self.current_analysis_tab()].analysis_thread.isRunning():
RuntimeError: wrapped C/C++ object of type QThread has been deleted
Aborted (core dumped)
```
- [x] One cannot put more than 3 digits into a slider widget. E.g. Setting a beam energy > 1e3 MeV in the `track fitting tab is impossible, fixed in e3a2bfbfc2a2014fdebf11edd403ba8ea11f58c7.
- [x] The std. track selection in track fitting tab leads to a 100 % efficiency, since only tracks with a dut hit are used. This is not how the track selection usually works (in script mode), fixed in 226356d19164f475c7d816b34ad24a64607dfd5d
- [x] Exception is raised if the value of the slider is set in the respective edit via  pressing `Return`  for e.g. `Filter size` option in `Noisy Pixel Tab`. This is due to incorrectly assigned widgets. Partially fixed in f0a3fdd5076ec9fc120a85573a9bcc207d913ecf 
```
Traceback (most recent call last):
  ...
  File "/home/leloup/git/testbeam_analysis/testbeam_analysis/hit_analysis.py", line 175, in generate_pixel_mask
    blurred = median_filter(occupancy.astype(np.int32), size=filter_size, mode='constant', cval=0.0)
  File "/home/leloup/miniconda2/lib/python2.7/site-packages/scipy/ndimage/filters.py", line 1282, in median_filter
    origin, 'median')
  File "/home/leloup/miniconda2/lib/python2.7/site-packages/scipy/ndimage/filters.py", line 1164, in _rank_filter
    sizes = _ni_support._normalize_sequence(size, input.ndim)
  File "/home/leloup/miniconda2/lib/python2.7/site-packages/scipy/ndimage/_ni_support.py", line 65, in _normalize_sequence
    raise RuntimeError(err)
RuntimeError: sequence argument must have length equal to input rank
```
- [x] Allow selection hit duts != align duts, fixed in 4494f1e8d65e81f2a06a9a3a779d18bd4d6f443c
- [x] Saving session crashes  after interactive prealignment due to python queue, fixed in ee48612c4c15c331af8283f4524c07eed6f8ab40
- [x] Vitables does not open on linux although it is installed due to using MiniConda vitables instead of system installation, fixed in 5402571f2c99b204df780bef4bc1f41ac8bb7bbb
- [x] Loading session crashes when noisy pixel removal was skipped for at least one DUT in saved session due to plotting, fixed in 5402571f2c99b204df780bef4bc1f41ac8bb7bbb
- [x] Vitables does not find files due to files paths being in dict instead of list when loading from session, fixed in de4925d5345701182a7673aea34cf044ff5e1bc0
- [x] Changing settings after setup tab is completed enables all tabs, fixed in 020ecab0ff3069bf1a2ee98cbffae7443a4356cf
- [x] Skipping alignment in settings causes crash, fixed in b030c14e4508c5f4e259d6197942b2236b283289
- [x] RAM consumption for plotting `track_finding` results too high (see comment below), fixed in e588cdff50ad1da4c8bdead651ef5a947a241a96, related  to #102

**Comment by DavidLP** [comment]
Since GUI a new feature and not the usual way to use TBA I label this an enhancement.

**Comment by leloup314** [comment]
All tracebacks and error outputs should be fixed with ec450aa441ba7f9780f00ec27425d64f2977b7e6. This was already implemented, I simply forgot to connect the signals that pass the exceptions, errors, etc. to the main thread.

**Comment by leloup314** [comment]
The plot for tracks is made from the `TrackCandidates_prealigned.h5` after first doing `find_tracks`. I just put this there temporarily, I also do not understand what the parameter `dut` of type `uint` in function [`plot_events`](https://github.com/SiLab-Bonn/testbeam_analysis/blob/development/testbeam_analysis/tools/plot_utils.py#L619) is supposed to accomplish, since I thought that we want to plot tracks in at least several DUTs but not only one. Maybe one can not use this immediately after `find_tracks`

**Comment by DavidLP** [comment]
We are fitting tracks for a certain DUT, with independent cuts. This parameter should just select the tracks we fitted for a certain DUT.

**Comment by leloup314** [comment]
Crash of python.exe under Windows is most likely due to non-threadsafe behavior of the logging handler + streamer object. @DavidLP Please check if GUI still crashes if you comment out [this line](https://github.com/SiLab-Bonn/testbeam_analysis/blob/gui/testbeam_analysis/gui/main.py#L84) in `main.py`.

**Comment by DavidLP** [comment]
Unfortunately is does not help and still crashes.

**Comment by leloup314** [comment]
I have to check, I guess logging from other than main thread has to be dealt with, even though it's not redirected to a QWidget, it fails because it logs from other than main thread to console of Eclipse etc. I will reimplement analysis without multi-threading to check that this is the problem.

**Comment by leloup314** [comment]
@DavidLP can you check whether `python.exe` still crashes under Windows for `THREADING_MODE = 'Pool'`? Is already default in latest commit. Thank you!

**Comment by DavidLP** [comment]
It does not crashing anymore, but the GUI is not responding during analysis.

**Comment by leloup314** [comment]
It was not supposed to be responding during analysis since this is not a multi-threading approach but only a reimplementation (or regression) to check whether the crashing of python has something to do with multi-threading under windows. I will try to implement something thread-safe for windows regarding logging from other than main thread. I guess the way I do it right now is not really thread-safe

**Comment by leloup314** [comment]
Crash of python.exe under Windows due to ParallelAnalysisWidget and the way threads are accessed in it.

**Comment by DavidLP** [comment]
Since this is now in `development` bug are considered bug.

**Comment by leloup314** [comment]
Windows and Linux handle QThreads differently. Each Qt application (GUI) has a global `QThreadPool` which handles all `QThread`s ([see here](http://pyqt.sourceforge.net/Docs/PyQt4/qthreadpool.html)) Creating instances of `QThread` in a loop under Windows causes the GUI to crash due to different settings of the global `QThreadPool` (e.g. maxThreadCount) or timing issues (settings are not changed in time) , I guess. Better approach would be to use `QThreadPool` and `QRunnable` for GUI-multithreading ([see here](https://martinfitzpatrick.name/article/multithreading-pyqt-applications-with-qthreadpool/)), which enables an automatic handling of threads independent from the OS.

**Comment by DavidLP** [comment]
Go for it ;-)

**Comment by leloup314** [comment]
@DavidLP What are the circumstances of:
`Traceback (most recent call last):
  File "main.py", line 649, in run_consecutive_analysis
    if self.tw[self.current_analysis_tab()].analysis_thread.isRunning():
RuntimeError: wrapped C/C++ object of type QThread has been deleted
Aborted (core dumped)`
`CTRL-R` works for me when I just press it under Linux and Windows

**Comment by DavidLP** [comment]
After everything ran I pressed it.

**Comment by leloup314** [comment]
Okay, fair enough :smile: , fixed in d14320cef20eac47f88a0dc6194ea41f42366a6f

**Comment by leloup314** [comment]
@DavidLP How should the std. track selection look like? In the [example](https://github.com/SiLab-Bonn/testbeam_analysis/blob/monopix/testbeam_analysis/examples/monopix_efficiency.py), the `selection_track_quality` is also a matrix like `align_duts` etc., right now its a slider. Should this also be changed?

**Comment by leloup314** [comment]
@DavidLP @laborleben The interactive pre-alignment does not work in the GUI, even if it is started from the main GUI thread, because the `matplotlib` GUI starts a new `event loop` which does not work since there can only be one event loop. A sub-window for the interactive pre-alignment has to be implemented, I guess. Should I implement it to be also used in the script-version of `testbeam analysis`?

**Comment by DavidLP** [comment]
> How should the std. track selection look like?

It should be an `n_duts x n_duts` matrix.
Fit DUTs should be tick box per DUT.

>Should I implement it to be also used in the script-version of testbeam analysis?

Interactive pre-alignment code is nevertheless very ugly. Rewriting it with better interface/calculation seperation would be good.

**Comment by leloup314** [comment]
>It should be an `n_duts x n_duts` matrix.

What are the values for track selection? 0, 1 and 2 like [here?](https://github.com/SiLab-Bonn/testbeam_analysis/blob/development/testbeam_analysis/track_analysis.py#L175-L181). Should I implement an `OptionSpinBox` widget in which integer values from 0-2 can be selected and which can also be displayed in a matrix? 

>Fit DUTs should be tick box per DUT.

This is already done.

**Comment by leloup314** [comment]
Plotting `track_finding` results into GUI consumes too much memory
![selection_0134](https://user-images.githubusercontent.com/18701435/36381344-8b1b850e-1585-11e8-98d7-04ace5fb935a.png)

**Comment by DavidLP** [comment]
Congratulations! I close this issue, gui is stable enough to get one issue per bug.

**Comment by leloup314** [comment]
Yay! ;)
