### ISSUE TITLE
Crash during map_cluster

### ISSUE THREAD

**Issue by leloup314** [SiLab-Bonn/testbeam_analysis#73]
![selection_0045](https://cloud.githubusercontent.com/assets/18701435/26465095/4355832a-418a-11e7-9a02-b88ca0219a6b.png)
![selection_0050](https://cloud.githubusercontent.com/assets/18701435/26465098/45aba348-418a-11e7-89bc-e47ea525e7f0.png) When running the `fei4_telescope` example script (above) and when executing the pre-alignment in the GUI (without multi-threading, just pooling to be safe, below) this error  
occurs and the analysis crashes.

**Comment by DavidLP** [comment]
Do a `setup.py develop` to recompile the C++ parts to support the new data type.

**Comment by laborleben** [comment]
Optionally run `git clean -dxf` to remove all non-git-tracked files. Be careful, if you made changes to the pixel_clusterizer folder.

**Comment by DavidLP** [comment]
> Be careful, if you made changes to the pixel_clusterizer folder.

We are talking about TBA not `pixel clusterizer`. Git clean should not be called on that ;-)

**Comment by themperek** [comment]
Maybe do not use c but numba ;-)

**Comment by DavidLP** [comment]
Numba also has quite some bugs and quirks (e.g. https://github.com/numba/numba/issues/1653). C is much more mature and if it crashes it is your fault. If Numba crashes it usually cannot be fixed by you and only circumvented ;-) Also C is twice as fast in real world applications.
