### ISSUE TITLE
Function plot_checks() missing.

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/testbeam_analysis#97]
Function ```plot_utils.plot_checks()``` is missing.

Used here: https://github.com/SiLab-Bonn/testbeam_analysis/blob/ed5def4ab3990d080818c935febccffb5fc231cc/testbeam_analysis/hit_analysis.py#L122

**Comment by DavidLP** [comment]
Why is this a regression? It never worked as intended.

**Comment by leloup314** [comment]
I added `plot_checks()` to `plot_utils` in the `gui` branch

**Comment by leloup314** [comment]
This is now in `development` again. Can this be closed?

**Comment by laborleben** [comment]
Sure :-)
